POST http://127.0.0.1:8000/bands/
Content-Type: application/json

{
    "name": "Aji",
    "genre": "Rock",
    "albums": [
        {
            "title": "Rock Star",
            "release_date": "2018-05-28"
        },
        {
            "title": "Sprites",
            "release_date": "2018-06-15"
        }
    ]
}

###
GET http://127.0.0.1:8000/bands
